let x = 13, y = 20;
let resultado = x + y;
let mensagem = "A soma de " + x + " e " + y + " é " + resultado;
console.log(mensagem);
resultado = x - y;
mensagem = "A subitração de " + x + " e " + y + " é " + resultado; 
console.log(mensagem);
resultado = x * y;
mensagem = "A multiplicação de " + x + " e " + y + " é " + resultado;
console.log(mensagem);
resultado = x / y;
mensagem = "A divisão de " + x + " e " + y + " é " + resultado;
console.log(mensagem);